# -*- coding: utf-8 -*-
"""Data cleaning.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YIoTXPHfg9Xf-CLqowfdLYeL9Gy0hFgW
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/auto-mpg.csv")

df.shape

df.info()

df.dtypes

df.describe()

df.isnull().sum()

df.sample(10)



df['horsepower']=df['horsepower'].astype(float)

df['horsepower']=df['horsepower'].replace(to_replace='?',value=np.nan)

df.info()

median1=df['horsepower'].median()

df['horsepower'].replace(np.nan,median1,inplace=True)

df.sample(10)

median1

df.drop('car name',axis=1,inplace=True)

df.head()